### ISSUE TITLE
12 Vram 

### ISSUE THREAD

**Issue by wcarletsdrive** [AlbertSuarez/dreambooth-stable-diffusion#1]
Does this work for 12 VRAM? If not, can you implement it without 8 bit Adam so we don’t lose quality? No deepspeed either please

**Comment by AlbertSuarez** [comment]
Hey @wcarletsdrive, it works. My own GPU is a 12GB VRAM one and it only needs ~4.2GB, so 12GB works in the same way 6GB would do.

**Comment by wcarletsdrive** [comment]
Wow thanks for making this! My last question is, does this use diffusers or no? I was wondering if it worked the same way (their algorithm) Joe Penna and kanewallmann made theirs?
